name: codspeed-benchmarks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependenciesgit st
        run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-codspeed
            pip install .
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest tests/benchmark.py --codspeed